---

sudo: required
language: python
python:
  - "2.7"
script:
  - pip install ansible
  - sudo su travis -c 'source ~/virtualenv/python2.7/bin/activate; ansible-playbook -i tests/inventory -vvvv tests/test.yml --limit xenial'
  - >
      sudo su travis -c 'source ~/virtualenv/python2.7/bin/activate; ansible-playbook -i tests/inventory -vvvv tests/test.yml --limit xenial'
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)

  - sudo su travis -c 'lxc exec stretch -- apt install -y python sudo'
  - sudo su travis -c 'source ~/virtualenv/python2.7/bin/activate; ansible-playbook -i tests/inventory -vvvv tests/test.yml --limit stretch'
  - >
      sudo su travis -c 'source ~/virtualenv/python2.7/bin/activate; ansible-playbook -i tests/inventory -vvvv tests/test.yml --limit stretch'
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
